### ISSUE TITLE
[Nanaky animaux] Rétrécir le singe de Nanaky

### ISSUE THREAD

**Issue by roiofthesuisse** [roiofthesuisse/Polaris03#3]
Il doit avoir la bonne taille relativement au chara du héros.

**Comment by NanakyTim** [comment]
C'est vrai qu'elle est beaucoup trop grosse...




... Mon image de singe. Je dois aussi finaliser son chara en déplacement (et celui où il fait pipi dans un bocal).

**Comment by roiofthesuisse** [comment]
Si tu n'utilises pas mon super magnifique éblouissant singe, je le recyclerai dans Kujira ~

**Comment by NanakyTim** [comment]
J'ai rétréci mon singe et je lui ai ajouté des contours (+ quelques détails).

[http://img110.xooimage.com/files/5/e/4/nana_singe_marche-50f9e4f.png](url)

Plus qu'à l'animer en marche.

**Comment by roiofthesuisse** [comment]
Ok.
Faire attention qu'il n'ait pas la même couleur que la chaise.
La dernière fois, la chaise était de la même couleur alors on ne comprenait pas ce que ça représentait.

D'autant plus qu'il miaule...

**Comment by NanakyTim** [comment]
La chaise est grise donc normalement y'aura pas de problème
