### ISSUE TITLE
[Global] Porte aux pass

### ISSUE THREAD

**Issue by roiofthesuisse** [roiofthesuisse/Polaris03#6]
Située dans le mini-HUB RotS/Némau, en haut d'un escalier.

**Comment by sriden** [comment]
C'est fait. À voir si le design de la porte vous convient, ou encore s'il faut retravailler les textes associés.

**Comment by roiofthesuisse** [comment]
Je prendrai la main pour faire l'escalier, histoire que la forme de la pièce suggère l'importance de la porte.
