### ISSUE TITLE
[Criket robot] Bloqué sur la flaque d'acide

### ISSUE THREAD

**Issue by roiofthesuisse** [roiofthesuisse/Polaris03#7]
Quand on est sur la passerelle (ligne du milieu), et qu'on appuie sur Z pendant le saut vers le bas :

http://img.xooimage.com/files110/1/2/2/uiyguyfgytdftre-4c4d8f4.png

On est bloqué dans la flaque d'acide : bug bloquant qui oblige à F4. :-- Ça le fait sur la flaque à gauche de la passerelle aussi.
Peut-être qu'on peut le corriger avec un event parallèle qui dit "si coordonnées du héros = machin ; machin (coordonnées correspondant à chacune des deux flaques d'acide) => alors : déplacer event (héros), traverse tout ON + un pas vers le bas + traverse tout OFF".

**Comment by sriden** [comment]
Ce bug est obsolète puisqu'il n'y a plus de flaque d'acide dans la nouvelle version de sa partie. Plus besoin de ce ticket donc. :P
